### ISSUE TITLE
arduino ebuild need  "<dev-util/astyle-3" but only version 3.0.1 is in portage

### ISSUE THREAD

**Issue by bdouxx** [mapmot/arduino-overlay#13]
```
JDEPEND="
...
        <dev-util/astyle-3[java]
..."

```
```
eix -s astyle
[U] dev-util/astyle
     Available versions:  3.0.1 {examples java static-libs ELIBC="FreeBSD"}

```

**Comment by mapmot** [comment]
I did a quick test with astyle-3 and it doesn't work, so I've added astyle-2.06 to the overlay.

This is with astyle-3.0.1:

```
java.lang.UnsatisfiedLinkError: no astylej in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at cc.arduino.packages.formatter.AStyleInterface.<clinit>(AStyleInterface.java:44)
	at cc.arduino.packages.formatter.AStyle.<init>(AStyle.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at processing.app.Editor.createToolMenuItem(Editor.java:967)
	at processing.app.Editor.addInternalTools(Editor.java:990)
	at processing.app.Editor.buildToolsMenu(Editor.java:733)
	at processing.app.Editor.buildMenuBar(Editor.java:498)
	at processing.app.Editor.<init>(Editor.java:252)
	at processing.app.Base.handleOpen(Base.java:840)
	at processing.app.Base.handleOpen(Base.java:826)
	at processing.app.Base.handleOpen(Base.java:822)
	at processing.app.Base.handleNew(Base.java:759)
	at processing.app.Base.<init>(Base.java:465)
	at processing.app.Base.main(Base.java:144)
```
